# Generated by Django 4.2 on 2023-05-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='position_location',
        ),
    ]
