# Generated by Django 4.2 on 2023-06-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_location_job_position_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='img_src',
            field=models.CharField(default='https://jomdevassets.s3.eu-west-2.amazonaws.com/OIG+(5).jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='job.company'),
        ),
    ]
